# Generated by Django 3.1.2 on 2020-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('file_path', models.TextField(verbose_name='Ссылка на видео файл фильма')),
                ('srt_path', models.TextField(verbose_name='Ссылка на файл с субтитрами')),
            ],
        ),
    ]
